### ISSUE TITLE
Create new MRA files for CPS1 games

### ISSUE THREAD

**Issue by jotego** [jotego/jtcps#151]
JTCPS1 was the first core to extract information from MAME in order to create the MRA files. Since then JTFRAME has advanced a long way to make this a standard step of core development. JTCPS1 MRA files are not well supported now as they are not covered by the new workflow and they have had merges in JTBIN.

**Missing MRA features**
- Button names
- _ccw_ annotations for vertical games

**Tasks**
- [ ] Export the header section of current MRA files into a new _mame2mra.toml_ file
- [ ] Add button names
- [ ] Correct DIP switch names
- [ ] Add flow for custom MRA files
- [ ] Keep MRA files for DMA speed tests

**Comment by Toryalai1** [comment]
This might be helpful: 
https://github.com/jotego/jtbin/pull/298
